### ISSUE TITLE
nexusUser in build.gradle

### ISSUE THREAD

**Issue by alisayani** [bi-foundation/factom-java#9]
**Issue**
When a user tries to download the repo and try to open it in intellij, it shows following error 
"Could not get unknown property 'nexusUser' for object of type org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension."

**Suggestion**
It would be good if you do following change in build.gradle file:
nexusUser
to 
credentials.nexusUser

**To Reproduce**
1) Download the repository
2) Import/Open the repository folder in intellij

**Expected behavior**
It should import/open without any error.

**Additional context**
You have updated the nexusPassword to credentials.nexusPassword but you probably missed nexusUser and as it is not even a string so it is showing this error (mentioned above).

**Comment by LDMGN** [comment]
Working on this in https://github.com/bi-foundation/factom-java/pull/10
There seems to be an issue with our CI configuration however, so it needs some debugging / investigation before merging.
